export const TITLES: string[] = [
  'May the Force be with you.',
  "I'll be back.",
  "Here's looking at you, kid.",
  "You can't handle the truth!",
  'To infinity and beyond!',
  'My precious.',
  "Life is like a box of chocolates, you never know what you're gonna get.",
  'I am your father.',
  "There's no place like home.",
  "You're gonna need a bigger boat.",
  "Here's Johnny!",
  'Houston, we have a problem.',
  'Bond. James Bond.',
  'Why so serious?',
  'Say hello to my little friend!',
  'Hasta la vista, baby.',
  'I see dead people.',
  'You talking to me?',
  'Keep your friends close, but your enemies closer.',
  "I'll never let go, Jack.",
];

export const AUTHORS: string[] = [
  'John Smith',
  'Emily Johnson',
  'Michael Williams',
  'Jessica Brown',
  'Daniel Jones',
  'Sarah Davis',
  'Christopher Miller',
  'Amanda Wilson',
  'Matthew Taylor',
  'Laura Anderson',
  'David Martinez',
  'Jennifer Thompson',
  'James Garcia',
  'Linda Hernandez',
  'Robert Lopez',
  'Michelle Gonzalez',
  'William Perez',
  'Karen Sanchez',
  'Mark Ramirez',
  'Angela Torres',
];

export const BODIES: string[] = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sagittis a leo et pretium. Vivamus at facilisis est. Nulla fermentum leo non ligula porttitor bibendum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur in mi quis justo aliquam consectetur vitae at odio. Donec eget facilisis ipsum. Sed fermentum sapien ante, eget gravida mauris elementum a. Vestibulum tortor lorem, ultrices at efficitur fermentum, tempor vitae augue. Proin tincidunt quam eget libero vulputate, vel mollis turpis euismod. Vivamus at leo sed diam pellentesque mollis.',
  'Ut eget neque sagittis purus cursus dictum. Cras sit amet libero mattis, semper felis vitae, varius nulla. Pellentesque aliquet gravida nulla, sed hendrerit ipsum pulvinar commodo. Maecenas finibus diam nec consectetur pharetra. Nulla facilisi. Pellentesque maximus volutpat egestas. Sed ut odio sit amet nunc tempus porttitor eget a nibh.',
  'Vestibulum mollis dictum libero eget iaculis. Nulla feugiat, dolor a rutrum varius, metus magna volutpat sapien, in tempus lorem tortor sit amet risus. Morbi feugiat, ligula a condimentum vestibulum, lacus lacus facilisis tortor, in lacinia elit mauris mollis ipsum. Integer dictum consequat nisl ut venenatis. Morbi felis tortor, convallis eu tristique non, accumsan mollis enim. Cras id sapien lacinia, volutpat mauris id, ultrices lorem. Nam bibendum tristique urna nec cursus.',
  'Sed vel enim in libero viverra interdum. Etiam nec dolor eu urna lacinia vehicula non in tortor. Cras tempor maximus erat quis tempus. Ut nec lectus commodo, viverra magna ut, porta neque. Aenean congue semper ligula. Morbi fringilla pellentesque ipsum sit amet porta. Mauris aliquet nunc elementum lectus scelerisque, sed consectetur diam cursus. Duis fermentum fringilla dolor, vel tempus quam dapibus eu.',
  'Vestibulum condimentum arcu vitae mauris consequat bibendum. Duis eget augue blandit, fermentum ipsum sed, faucibus urna. Nam pulvinar euismod facilisis. Vestibulum lacinia sagittis porta. Praesent et nibh et mi blandit ultrices eget non neque. Aliquam volutpat neque id ante vehicula maximus. Ut est nisi, tincidunt vitae fringilla vel, volutpat et eros. Etiam ut tincidunt est. Sed viverra nunc at eros vestibulum, ultrices pellentesque sem feugiat. Aliquam tempor eget massa a tempus. Praesent sed interdum sapien. In hac habitasse platea dictumst. Nunc in venenatis diam, non semper nulla. Proin congue finibus orci quis tempor.',
  'Sed at libero purus. Cras nulla lectus, viverra at gravida nec, ultricies eu purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam pretium ligula enim, eget pulvinar lacus lacinia id. Praesent iaculis a sem in cursus. Phasellus sit amet pellentesque purus. Proin sit amet nisl at erat ultrices placerat. Vivamus gravida non augue eu mollis. Nam non euismod dolor, vitae placerat risus. Nullam fringilla lorem id dolor malesuada tincidunt. Sed elementum bibendum tortor quis dapibus. Donec hendrerit mi dui, nec rutrum metus malesuada id. Morbi pulvinar vehicula sem ut tempus.',
  'Phasellus vitae eleifend orci, ac viverra ex. Mauris non luctus magna. Nunc eleifend metus orci, vel fringilla sapien blandit eget. Nullam nec pulvinar turpis. Donec dapibus vulputate finibus. Donec dictum sit amet erat eget mattis. Phasellus porta maximus libero eu fringilla.',
  'Integer ante odio, convallis sit amet luctus viverra, congue nec libero. Integer pretium, sapien sit amet suscipit malesuada, nisi eros aliquet ipsum, in bibendum dolor est eget quam. Nunc non malesuada magna. Etiam eu nunc finibus, sodales erat porttitor, faucibus quam. Nunc eget laoreet tellus. Duis convallis mi a convallis sollicitudin. Pellentesque ut ipsum elit. Quisque nibh tellus, rutrum in molestie eu, sodales ut ligula. Proin volutpat eros eu ullamcorper lobortis. Nunc pharetra tempor dapibus. Proin sed nisi bibendum augue euismod auctor. Sed eget augue a nisi semper ultrices porttitor sed nisl. Mauris fringilla sed lectus eget semper.',
  'Phasellus lectus ante, ultrices eget dapibus a, scelerisque eget tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus ac libero aliquet, varius nisi vitae, lobortis mauris. Aenean eleifend varius rutrum. In hac habitasse platea dictumst. Nulla facilisi. Phasellus feugiat lacinia ante at egestas. Donec dictum enim eu risus eleifend, quis semper leo bibendum. Morbi rutrum vestibulum neque. Pellentesque in enim vestibulum, malesuada diam in, dictum augue. Etiam viverra rutrum molestie. Sed congue blandit arcu, sed dictum justo tincidunt sed. Vivamus massa sapien, dictum id lobortis et, ultricies quis diam. Ut mollis nisl tortor, a tincidunt mauris rhoncus eu.',
  'Integer hendrerit bibendum ornare. Aliquam auctor ante nec nulla suscipit pharetra. Nulla rhoncus justo in est auctor, ac pellentesque urna euismod. Nulla vitae pulvinar felis, ac semper eros. Aliquam tincidunt magna justo, eget pulvinar elit ullamcorper nec. Praesent elementum blandit purus et vehicula. Aliquam risus odio, lacinia eget pellentesque maximus, porta id augue. Cras lacinia sapien convallis enim bibendum, ac pellentesque sapien aliquet. Aenean sit amet magna fringilla, fermentum est vel, ullamcorper turpis. Curabitur egestas accumsan leo, vitae commodo lacus auctor eget. Sed eu imperdiet orci, ut lacinia libero. Morbi scelerisque vulputate tellus a hendrerit.',
  'Etiam accumsan tellus at turpis ultricies, vitae rutrum est pulvinar. Aenean dapibus libero consequat scelerisque consectetur. Sed massa nisl, porttitor in fringilla ut, mollis ac eros. Morbi commodo luctus nibh id fermentum. Nam est arcu, accumsan non semper id, aliquet in ipsum. Quisque rhoncus velit eget sem hendrerit, in dapibus turpis vulputate. In hac habitasse platea dictumst. In egestas lorem tellus, nec molestie dolor sagittis sit amet. Donec maximus dapibus nunc, molestie molestie diam. Nullam mauris nisi, lacinia non lobortis sit amet, dictum sed odio. Sed vel consequat odio. Nullam dignissim feugiat efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  'Proin quam metus, gravida in volutpat quis, euismod semper urna. Quisque non malesuada dui, vel dignissim neque. Nam faucibus lacus eget venenatis bibendum. Aliquam erat augue, luctus nec consectetur at, luctus ac augue. Aliquam eu nibh eu dolor congue rutrum vel venenatis dolor. Aliquam erat volutpat. Morbi ut faucibus augue. Quisque at convallis turpis. Aenean sed malesuada neque, vel sodales urna. Pellentesque sed augue non sapien fermentum varius ut non dolor. Nam cursus dictum diam, in feugiat quam. Vivamus mollis aliquet dapibus. Donec a hendrerit erat, sit amet sagittis nisi. Morbi euismod enim nec tristique ultricies. Cras vestibulum bibendum nulla in placerat. Suspendisse gravida eu nulla porttitor dapibus.',
  'Integer tincidunt elit eu nisl auctor maximus. Nunc in lorem a neque rutrum tincidunt non ut felis. Sed in dui diam. Pellentesque non orci porttitor, viverra sem sed, porta lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean ornare libero eget sem pretium convallis. Proin vulputate sollicitudin placerat. Donec commodo, lorem eget laoreet iaculis, metus ante porta leo, sit amet varius orci dolor vel nunc. In ullamcorper turpis quis elit bibendum, a eleifend elit pretium. Morbi at tincidunt enim.',
  'Nullam euismod lobortis vulputate. Donec ac placerat neque, et tincidunt elit. Nunc lectus lorem, congue vitae eros non, efficitur commodo ligula. Aenean convallis nulla id dictum pharetra. Donec porta at odio nec aliquet. Suspendisse vel neque felis. Nulla facilisi. Fusce ornare ligula non massa vestibulum, id interdum orci accumsan. Phasellus gravida lobortis fringilla. Donec feugiat feugiat sapien eu dignissim.',
  'Ut ex risus, ultricies id ornare a, dignissim ut dui. Nulla a semper mi. Vestibulum placerat neque et lorem accumsan gravida. Vestibulum finibus at diam suscipit mattis. Curabitur suscipit placerat odio accumsan rhoncus. Fusce vehicula in nulla eu vehicula. Curabitur ac sagittis tellus. Maecenas tristique elementum nisi, vulputate commodo nisl ultricies eget. Nam gravida non risus eu tincidunt. Suspendisse lacinia pellentesque nulla. Praesent sit amet neque placerat, varius arcu sit amet, ornare massa. Nulla molestie viverra ligula, in aliquet neque gravida in. Sed nec facilisis dui.',
  'Nullam dapibus volutpat turpis, ut efficitur ligula dapibus at. Cras in sapien suscipit, ultricies lorem et, finibus diam. Phasellus tristique ex ac eros ultricies, vitae commodo ipsum lacinia. Mauris venenatis enim ac ante venenatis elementum. Vivamus condimentum, mi nec suscipit hendrerit, tortor nulla tincidunt ex, id viverra lectus risus quis urna. Sed auctor tincidunt turpis, nec vestibulum nisl vehicula a. Nulla facilisi. Sed in nunc ipsum. Duis non sem at nibh finibus gravida ut nec ipsum. Fusce tincidunt magna sit amet vestibulum hendrerit.',
  'Pellentesque quis turpis nec mauris facilisis ultricies. Sed ac arcu eu mauris bibendum dignissim. Nullam eleifend, magna non facilisis efficitur, ligula velit iaculis nulla, a varius urna libero quis quam. Cras efficitur tempus ipsum id bibendum. Aliquam sodales sit amet dui eu dignissim. Mauris non sapien vel libero tristique scelerisque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
  'Curabitur mattis justo nec aliquet egestas. Maecenas suscipit feugiat turpis, nec hendrerit velit posuere nec. Aenean ut ligula nec ligula congue malesuada. Duis suscipit dapibus efficitur. Morbi laoreet commodo magna, non dignissim ipsum laoreet nec. Duis rutrum ultricies libero, nec sodales dui pellentesque eu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam tincidunt ligula nec felis fermentum tincidunt. Vivamus et nisi in velit tincidunt consequat. Cras sed orci ut purus feugiat congue. Maecenas luctus mauris et dictum feugiat. Suspendisse in ligula dolor. Ut placerat mauris nec sapien tincidunt, eget sodales dui ultrices. Fusce vel vehicula lacus, non laoreet nibh. Fusce vel justo in nisi fermentum fermentum ut nec dui.',
  'Suspendisse potenti. Aliquam eleifend eleifend lectus, vitae lobortis eros. Ut tincidunt nisi velit, vel vehicula neque luctus vel. Sed blandit lorem ac nisi bibendum, non maximus velit pharetra. Donec eget pulvinar tortor, id ultrices neque. Cras tincidunt elementum velit, ut suscipit sem viverra vel. Duis efficitur, ligula sit amet laoreet bibendum, mauris urna fermentum nisl, at vestibulum nibh risus sit amet orci. Curabitur ut felis vitae nibh pellentesque malesuada. Praesent volutpat dolor ligula, eu egestas mauris congue sed. Nam id posuere lacus, id finibus lorem. Donec euismod tellus vel tristique sollicitudin. Morbi consectetur felis nec leo blandit fringilla. Nullam sagittis felis eu orci sodales feugiat. Fusce sit amet congue lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
  'Phasellus quis erat convallis, interdum lacus vel, tincidunt erat. Proin sodales magna quam, eu congue sem varius in. In nec ullamcorper mi. Vestibulum in eleifend neque. Quisque elit risus, ultrices a erat bibendum, consectetur elementum tortor. Nullam porta mi non tortor aliquet, sed lacinia massa iaculis. Sed varius feugiat enim. Suspendisse sit amet massa ullamcorper, consequat quam ut, imperdiet nisi. Quisque porta dignissim gravida. Aliquam volutpat lectus a est pharetra hendrerit in eget lacus. Curabitur sit amet eros et eros tincidunt maximus.',
];
